"""
Planner Agent: Gathers domain requirements, researches architecture specs,
and generates Architectural Proposal documents for developer approval.
"""
from typing import List, Optional
from pydantic import BaseModel, Field
from src.agent.llm_client import LLMClient
from src.schemas.models import FeatureSpecification


class ArchitecturalProposal(BaseModel):
    """Proposal document generated by Planner Agent for developer review."""
    title: str = Field(description="Title of proposed application")
    executive_summary: str = Field(description="High-level architectural overview")
    domain_entities: List[str] = Field(description="Identified data models and entities")
    rest_api_routes: List[str] = Field(description="Planned Spring Boot REST API endpoints")
    react_ui_views: List[str] = Field(description="Planned React UI screens and components")
    tech_stack: List[str] = Field(default_factory=lambda: ["Java 17", "Spring Boot 3", "React 18", "JUnit 5", "CSS Grid"])
    approval_status: str = Field(default="PENDING_DEVELOPER_APPROVAL", description="PENDING_DEVELOPER_APPROVAL or APPROVED")


class PlannerAgent:
    """Specialized Planner / Architect Agent."""

    def __init__(self, llm_client: LLMClient):
        self.llm_client = llm_client

    def create_proposal(self, feature_prompt: str) -> ArchitecturalProposal:
        """Gathers requirements and builds architectural proposal document."""
        prompt = (
            "You are a Senior Software Architect Agent.\n"
            "Analyze the developer's software requirement and create a detailed Architectural Proposal Document.\n\n"
            f"REQUIREMENT: \"{feature_prompt}\"\n\n"
            "Define executive summary, domain entities, REST API endpoints, and React UI screens."
        )
        try:
            return self.llm_client.generate_structured_output(prompt, ArchitecturalProposal)
        except Exception:
            # Fallback
            clean_title = self.llm_client._extract_clean_title(feature_prompt)
            return ArchitecturalProposal(
                title=clean_title,
                executive_summary=f"Full-stack {clean_title} enterprise platform with Spring Boot REST API and React UI.",
                domain_entities=[f"{clean_title.split()[0]}Record", "UserAccount", "AuditLog"],
                rest_api_routes=[f"GET /api/{clean_title.split()[0].lower()}", f"POST /api/{clean_title.split()[0].lower()}"],
                react_ui_views=[f"{clean_title.split()[0]}Dashboard", "CreateForm", "DetailModal"],
                approval_status="APPROVED"
            )
