from typing import List, Optional
from pydantic import BaseModel, Field


class IssueTicket(BaseModel):
    """Represents the bug ticket to be resolved."""
    title: str = Field(description="Title of the bug ticket")
    description: str = Field(description="Detailed issue description")
    stack_trace: Optional[str] = Field(default="", description="Stack trace if available")
    target_repo_path: str = Field(description="Absolute path to target repository")


class RepoContext(BaseModel):
    """Context gathered from analyzing the codebase."""
    repo_name: str
    file_tree: List[str] = Field(default_factory=list)
    build_system: str = Field(default="unknown")
    test_framework: str = Field(default="pytest")
    test_command: str = Field(default="pytest")
    linter_command: Optional[str] = Field(default=None)
    key_files_content: dict[str, str] = Field(default_factory=dict)


class ReproductionTest(BaseModel):
    """Output for Phase 3 (Reproduction Safety Gate)."""
    test_file_path: str = Field(description="Relative path where reproduction test should be saved")
    test_code: str = Field(description="Raw executable code for the standalone regression test")
    runner_command: str = Field(description="Command to execute this reproduction test")


class Diagnosis(BaseModel):
    """Root cause diagnosis generated by agent."""
    root_cause: str = Field(description="Brief explanation of the root cause")
    suspected_files: List[str] = Field(description="List of files suspected of containing the bug")


class PatchSubmission(BaseModel):
    """Output for Phase 4 / Phase 5 (Diagnose and Patch)."""
    diagnosis: Diagnosis = Field(description="Diagnosis detailing root cause and suspected files")
    patch_diff: str = Field(description="Strict unified git diff string to fix the bug")


class ValidationResult(BaseModel):
    """Result of Phase 5 validation (linting & test suite)."""
    success: bool = Field(description="True if all tests and linters passed cleanly")
    attempt_number: int = Field(default=1)
    reproduction_test_passed: bool = Field(default=False)
    suite_passed: bool = Field(default=False)
    console_output: str = Field(default="")
    error_log: Optional[str] = Field(default=None)


# --- Full-Stack Generator Schemas ---

class CodeFile(BaseModel):
    """Represents a generated source file."""
    file_path: str = Field(description="Relative path for the file e.g., src/main/java/com/app/OrderController.java")
    content: str = Field(description="Full source code content")
    description: str = Field(default="", description="Description of file purpose")


class FeatureSpecification(BaseModel):
    """User requirement parsed into structured architecture specification."""
    feature_title: str = Field(description="Title of the application feature")
    summary: str = Field(description="Summary of functional requirements")
    entities: List[str] = Field(default_factory=list, description="List of domain entities")
    api_endpoints: List[str] = Field(default_factory=list, description="List of REST API endpoints")
    ui_views: List[str] = Field(default_factory=list, description="List of React UI screens")


class SpringBootArtifacts(BaseModel):
    """Generated Java Spring Boot backend files and tests."""
    pom_xml: CodeFile = Field(description="Maven pom.xml file")
    java_files: List[CodeFile] = Field(default_factory=list, description="Controllers, Services, Repositories, Entities")
    test_files: List[CodeFile] = Field(default_factory=list, description="JUnit 5 + Mockito test files")


class ReactArtifacts(BaseModel):
    """Generated React frontend files and tests."""
    package_json: CodeFile = Field(description="NPM package.json file")
    component_files: List[CodeFile] = Field(default_factory=list, description="React components, styles, API service")
    test_files: List[CodeFile] = Field(default_factory=list, description="React testing library / Vitest tests")


class FullStackBundle(BaseModel):
    """Complete Full-Stack Application Bundle."""
    spec: FeatureSpecification
    backend: SpringBootArtifacts
    frontend: ReactArtifacts

